### ISSUE TITLE
Error: No table detected in the dashboard library when running sync

### ISSUE THREAD

**Issue by jordangarrison** [alloy-org/readwise#23]
# Problem

I'm unable to update my library since January 3rd. I've tried updating the plugin as well. I'm on the current version of the plugin as of February 14, 2024 2:31 PM. I've also tried running the sync all updates on Mobile, Web and Desktop all of which give the same error.

```
Error: No table detected in the dashboard library
```

I, however, do have a table in my Library dashboard. I also saw a new update to limit the books to 500 by default. To ensure I wasn't hitting this limit I increased my setting to 5000 and the issue persisted.

# Short investigation on the update

The only change I see is here: https://github.com/alloy-org/readwise/commit/7c9a4435d759dad6dd986e16791446db1c517dea#diff-2db8cac33fb46ac0ad2c550c55935cc50e0769f6f82f1c6655188962f27d9118R764

There is only one clue I saw at the first pass which was this update to the function definition to use `__` instead of `_`
https://github.com/alloy-org/readwise/commit/7c9a4435d759dad6dd986e16791446db1c517dea#diff-2db8cac33fb46ac0ad2c550c55935cc50e0769f6f82f1c6655188962f27d9118R764

The caller appears to still use `_` here https://github.com/alloy-org/readwise/commit/7c9a4435d759dad6dd986e16791446db1c517dea#diff-2db8cac33fb46ac0ad2c550c55935cc50e0769f6f82f1c6655188962f27d9118R792

# Browser console error

I noticed when I looked at the browser console the following function was giving the error

```js
  function _tableFromMarkdown(content) {
    console.debug(`_tableFromMarkdown(${content})`);
    let tableRegex = /^\s*\|(\s*\*\*[^|]+\*\*\s*\|)+$\n(\s*\|(.*\|)+$)+/gm;
    let tableMatch = content.match(tableRegex);
    if (!tableMatch) {
      console.error(`No table detected in the dashboard library`);
      throw new Error(`No table detected in the dashboard library`);
    }
    let lines = tableMatch[0].split("\n");
    if (lines.length < 2)
      return null;
    lines = lines.filter((row) => row.trim() !== "" && !row.trim().match(/^\s*\|([-\s]+\|\s*)+$/));
    if (!lines[0]) {
      console.error(`Dashboard has no meaningful rows: ${lines.join("\n")}`);
      throw new Error(`Dashboard has no meaningful rows: ${lines.join("\n")}`);
    }
    let headers;
    try {
      headers = lines[0].split("|").slice(1, -1).map((header) => header.trim().replace(new RegExp("\\*", "g"), ""));
    } catch (err) {
      if (err.name === "TypeError") {
        throw new Error(`${err.message} (line 887)`);
      }
    }
    const table = lines.slice(1).map((row) => {
      const cells = row.split(/(?<!\\)\|/).slice(1, -1).map((cell) => cell.trim());
      const rowObj = {};
      headers.forEach((header, i) => {
        if (cells[i] === "") {
          console.error(`Couldn't find a book property in the table.
Analyzing row: ${row}`);
          throw new Error(`Couldn't find a book property in the table.
Analyzing row: ${row}`);
        }
        if (cells[i] === void 0) {
          cells.push(`[No ${header}]`);
        }
        rowObj[header] = cells[i] || null;
      });
      if (rowObj.Cover) {
        rowObj.Cover = rowObj.Cover.replace(/!\[.+\|200]\(/mg, "![\\|200](");
      }
      return rowObj;
    });
    return table;
  }
```

**Comment by jordangarrison** [comment]
I was able to work around this by renaming my old dashboard note and having it recreate the dashboard. This is still not ideal behavior since it syncs every note again and saturates the "Today" and "This Week" notes views.

**Comment by lukkes** [comment]
@jordangarrison Thanks for reporting this! I would like to first exclude the possibility that the dashboard note itself is not corrupted. If a single heading in the dashboard note is empty (contains no tables), this error can be shown. 

If you have ~5000 readwise sources, such a heading might be easy to miss. Any way we can check if that's the case?

(I have to look into why we are creating empty headings in the first place, but confirming would be a good first step)

**Comment by lukkes** [comment]
Also @jordangarrison latest version of the plugin (should be live soon) attempts to detect if an empty heading is being written and will throw an error. Updating the plugin and attempting another sync would help diagnose 🙏

**Comment by jordangarrison** [comment]
@lukkes I have updated the plugin, but I'm having an issue with Amplnote itself now crashing when I attempt to open the Readwise Library Dashboard. I wonder if it's all the images trying to load?

**Comment by avichou** [comment]
still the same issue, maybe is it because i use a custom name ?

Error: No table detected in the dashboard lib
<img width="821" alt="Capture d’écran 2024-04-22 à 02 43 48" src="https://github.com/alloy-org/readwise/assets/86660671/cc1cbfcf-4d88-4025-8342-6d1423610e2c">
rary

**Comment by lukkes** [comment]
Hello @avichou! This error signals that _one_ of the headings found in the note is missing a table. We create multuple headings to group together books by year (and we also split those into multiple subgroups for performance considerations). 

Can you check if your dashboard has one of those empty headings?

**Comment by avichou** [comment]
> Hello @avichou! This error signals that _one_ of the headings found in the note is missing a table. We create multuple headings to group together books by year (and we also split those into multiple subgroups for performance considerations).
> 
> Can you check if your dashboard has one of those empty headings?

hi. I do not find it 

where can i check? i've verified the whole note but do not find an empty heading, unless im looking at it wrong

**Comment by lukkes** [comment]
@avichou thanks for checking! There are some mechanisms in place that attempt to prevent empty headings/tables from being written, so it's unclear how this might happen in the first place. Are you able to share your dashboard note privately (as markdown)?

**Comment by avichou** [comment]
> @avichou thanks for checking! There are some mechanisms in place that attempt to prevent empty headings/tables from being written, so it's unclear how this might happen in the first place. Are you able to share your dashboard note privately (as markdown)?
[Readwise Library Dashboard.md](https://github.com/alloy-org/readwise/files/15283643/Readwise.Library.Dashboard.md)

sure here it is !

**Comment by lukkes** [comment]
Thank you @avichou! This is very useful. It basically shows us that the dashboard ended up in a corrupt state (not sure yet _how_). I can see that first of all, the heading called "Readwise Book List" (the main one) is duplicated. Also, I see at least one empty sub-heading, that is the "(No highglights yet)" heading. 

None of these cases are expected, and there is code that should prevent at least one of them. If this happened, a likely culprit is that at some point you may have triggered a sync on a partially filled dashboard. In cases like this, I recommend removing all readwise-related notes and trying to sync again once (to get the dashboard back in place) and once more (to see if the error is still being generated).

If the error still appears after the fresh start, that means that I can look into what exactly about your particular list of books is generating this. If the error doesn't persist after the fresh start, it could be that the specific list of steps and their order were more of an edge case (and I can try to better treat those). 

In any case, there is little we can do to graciously fix the issue from the plugin code. If you don't want to fresh start, you could try to remove the empty "(No highlights yet)" heading, as well as everything below the second H1 called "Readwise Book List" and then try syncing again.

**Comment by avichou** [comment]
> Thank you @avichou! This is very useful. It basically shows us that the dashboard ended up in a corrupt state (not sure yet _how_). I can see that first of all, the heading called "Readwise Book List" (the main one) is duplicated. Also, I see at least one empty sub-heading, that is the "(No highglights yet)" heading.
> 
> None of these cases are expected, and there is code that should prevent at least one of them. If this happened, a likely culprit is that at some point you may have triggered a sync on a partially filled dashboard. In cases like this, I recommend removing all readwise-related notes and trying to sync again once (to get the dashboard back in place) and once more (to see if the error is still being generated).
> 
> If the error still appears after the fresh start, that means that I can look into what exactly about your particular list of books is generating this. If the error doesn't persist after the fresh start, it could be that the specific list of steps and their order were more of an edge case (and I can try to better treat those).
> 
> In any case, there is little we can do to graciously fix the issue from the plugin code. If you don't want to fresh start, you could try to remove the empty "(No highlights yet)" heading, as well as everything below the second H1 called "Readwise Book List" and then try syncing again.

thank you . i have removed everything to try again but unfortunately it seems notes cannot be permanently deleted and as such they are put into the trash... from where it is restored upon reinstallalation...which fucks things up again. 

I legitimately have no idea as to how and why I run into so so many issues with every software i touch, it's like i'm a non compliant genius or extremely unlucky, idk man 

let me try a fresh start again and see how it goes, okay? imma do this right now . i have no issue in doing a fresh start, dont worry ;-p

**Comment by avichou** [comment]
> Thank you @avichou! This is very useful. It basically shows us that the dashboard ended up in a corrupt state (not sure yet _how_). I can see that first of all, the heading called "Readwise Book List" (the main one) is duplicated. Also, I see at least one empty sub-heading, that is the "(No highglights yet)" heading.
> 
> None of these cases are expected, and there is code that should prevent at least one of them. If this happened, a likely culprit is that at some point you may have triggered a sync on a partially filled dashboard. In cases like this, I recommend removing all readwise-related notes and trying to sync again once (to get the dashboard back in place) and once more (to see if the error is still being generated).
> 
> If the error still appears after the fresh start, that means that I can look into what exactly about your particular list of books is generating this. If the error doesn't persist after the fresh start, it could be that the specific list of steps and their order were more of an edge case (and I can try to better treat those).
> 
> In any case, there is little we can do to graciously fix the issue from the plugin code. If you don't want to fresh start, you could try to remove the empty "(No highlights yet)" heading, as well as everything below the second H1 called "Readwise Book List" and then try syncing again.

seems to work now 

however something confuses me . when i want to sync again for new books and highilghits, am i supposed to invoke the "sync all command" from the original empty note i used to call.... or am i suppose to invoke it from the "Readwise Library Dashboard" note ?

**Comment by lukkes** [comment]
@avichou It shouldn't matter which note you invoke it from. The plugin will look for the existing note (by title and tags; if those are modified, it's not gonna find it) and update it.

**Comment by avichou** [comment]
> @avichou It shouldn't matter which note you invoke it from. The plugin will look for the existing note (by title and tags; if those are modified, it's not gonna find it) and update it. 

Oh wow , so I can do it from anywhere, really? That's damn nice

**Comment by lkind** [comment]
I also suddenly got this error last week. I deleted everything and did a fresh sync - which worked fine. But the bug is still there. I tried looking for the empy heading, but found it quicker to delete all and re-sync.

I have one feature request - that a plug-in for Roam has - which is really like. It pulls a random quote from Readwise and adds it to the DNP page (daily-jots). Which makes me rediscover quotes - better than the emails from Readwise.
